on: 
  push:
    branches:
      - main

name: Deploy website on push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Run react build script
      uses: actions/checkout@v2
          
    - run: npm i
    - run: npm run build
  
      env:
        CI: false
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build/
